<h1> Assignment 2</h1>
The objective of this assignment is to provide hands-on experience and proficiency in data analysis using Pandas. The assignment aims to enhance skills in data loading, exploration, selection, filtering, manipulation, and  grouping. The ultimate goal is to empower students to effectively navigate and analyze data, laying a solid foundation for more advanced data science tasks.

**Instructions:**
  - Do not remove comments such as # Task 1.1,# Task 1.2 etc. Provide your answers bellow these comments.
  - Use the provided variable names for your answers.
  - If the question is related to pandas operations, you are not allowed to use for loops.

## Task 1: Data Loading and Exploration (20 points)

1. **Loading Dataset**: Download the irirsh dataset from [here](https://drive.google.com/file/d/13s4W8dEaeV_fyOZ4uPf-dLkF9smw4zdW/view?usp=sharing) and Load it into a Pandas DataFrame named `iris_df`. (5pts)

2. **Displaying Data**: Print the first 10 rows of the DataFrame to get an initial overview of the dataset. (5pts)

3. **Checking Data Integrity**: Check the data types and null values in each column to ensure the dataset's completeness and consistency. (5pts)

4. **Summary Statistics**: Print the summary statistics for the numeric columns (mean, min, max, etc.) and for the categorical columns (count, unique, top, freq) providing a statistical snapshot of the dataset. (5pts)

In [2]:
import pandas as pd
#-------Grader only
url = 'https://drive.google.com/file/d/13s4W8dEaeV_fyOZ4uPf-dLkF9smw4zdW/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
iris_df = pd.read_csv(path)
#-------Grader only

# Task 1.1
iris_df = pd.read_csv(path)


# Task 1.2
display(iris_df.head(10))

# Task 1.3
null_values = iris_df.isnull()
number_of_null_values = null_values.sum()
display(number_of_null_values)

# Task 1.4
display(iris_df.describe(include='number'))
display(iris_df.describe(include='object'))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

       species
count      150
unique       3
top     setosa
freq        50

## Task 2: Data Selection and Filtering (20 points)

1. **Creating Subset**: Create a new DataFrame, `versicolor_df`, containing only rows where the species is 'versicolor'. (10pts)

2. **Column Selection**: Select and display only the 'sepal_length' and 'sepal_width' columns for the 'versicolor' species, narrowing down the focus to specific attributes. (5pts)

3. **Maximum Sepal Length**: Find the maximum sepal length for each species, offering insights into the range of sepal lengths across different species. (5pts)

In [21]:
# Task 2.1
versicolor_df = iris_df[iris_df['species'] == 'versicolor']
display(versicolor_df)

# Task 2.2
display(versicolor_df[['sepal_length', 'sepal_width']])

# Task 2.3
display(versicolor_df['sepal_length'].max())

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

    sepal_length  sepal_width
50           7.0          3.2
51           6.4          3.2
52           6.9          3.1
53           5.5          2.3
54           6.5          2.8
55           5.7          2.8
56           6.3          3.3
57           4.9          2.4
58           6.6          2.9
59           5.2          2.7
60           5.0          2.0
61           5.9          3.0
62           6.0          2.2
63           6.1          2.9
64           5.6          2.9
65           6.7          3.1
66           5.6          3.0
67           5.8          2.7
68           6.2          2.2
69           5.6          2.5
70           5.9          3.2
71           6.1          2.8
72           6.3          2.5
73           6.1          2.8
74           6.4          2.9
75           6.6          3.0
76           6.8          2.8
77           6.7          3.0
78           6.0          2.9
79           5.7          2.6
80           5.5          2.4
81           5.5          2.4
82           5.8          2.7
83           6.0          2.7
84           5.4          3.0
85           6.0          3.4
86           6.7          3.1
87           6.3          2.3
88           5.6          3.0
89           5.5          2.5
90           5.5          2.6
91           6.1          3.0
92           5.8          2.6
93           5.0          2.3
94           5.6          2.7
95           5.7          3.0
96           5.7          2.9
97           6.2          2.9
98           5.1          2.5
99           5.7          2.8

7.0

## Task 3: Data Manipulation (30 points)

1. **Adding New Column**: Add a new column to `iris_df` named 'sepal_ratio', representing the ratio of 'sepal_length' to 'sepal_width'. (10pts)

2. **Sorting Data**: Sort `iris_df` based on the 'petal_length' column in descending order, aiding in identifying patterns related to petal lengths. (10pts)

3. **Replacing Value**: Replace the 'versicolor' species with 'Iris-versicolor' in the 'species' column. (10pts)

In [12]:
# Task 3.1
iris_df['speal_ratio'] = iris_df['sepal_length']/iris_df['sepal_width']
display(iris_df.head(10))

# Task 3.2
print("3.2 sorted by petal length")
sorted_df = iris_df.sort_values('petal_length')
display(sorted_df)

# Task 3.3
iris_df['species'] = iris_df['species'].replace(to_replace='versicolor', value='Iris-versicolor')
display(iris_df['species'].value_counts())

   sepal_length  sepal_width  petal_length  petal_width species  speal_ratio
0           5.1          3.5           1.4          0.2  setosa     1.457143
1           4.9          3.0           1.4          0.2  setosa     1.633333
2           4.7          3.2           1.3          0.2  setosa     1.468750
3           4.6          3.1           1.5          0.2  setosa     1.483871
4           5.0          3.6           1.4          0.2  setosa     1.388889
5           5.4          3.9           1.7          0.4  setosa     1.384615
6           4.6          3.4           1.4          0.3  setosa     1.352941
7           5.0          3.4           1.5          0.2  setosa     1.470588
8           4.4          2.9           1.4          0.2  setosa     1.517241
9           4.9          3.1           1.5          0.1  setosa     1.580645

3.2 sorted by petal length

,sepal_length,sepal_width,petal_length,petal_width,species,speal_ratio
22,4.6,3.6,1.0,0.2,setosa,1.277778
13,4.3,3.0,1.1,0.1,setosa,1.433333
14,5.8,4.0,1.2,0.2,setosa,1.450000
35,5.0,3.2,1.2,0.2,setosa,1.562500
36,5.5,3.5,1.3,0.2,setosa,1.571429
...,...,...,...,...,...,...
131,7.9,3.8,6.4,2.0,virginica,2.078947
105,7.6,3.0,6.6,2.1,virginica,2.533333
117,7.7,3.8,6.7,2.2,virginica,2.026316
122,7.7,2.8,6.7,2.0,virginica,2.750000
118,7.7,2.6,6.9,2.3,virginica,2.961538

species
setosa             50
Iris-versicolor    50
virginica          50
Name: count, dtype: int64

## Task 4: Data Aggregation and Grouping (30 points)

1. **Grouping and Calculating Means**: Group `iris_df` by the 'species' column and calculate the mean for each numeric column within each group, providing insights into the average characteristics of each species. (10pts)

2. **Counting Species Occurrences**: Count the number of occurrences of each species in the original `iris_df`, giving an overview of the dataset's species distribution. (10pts)

3. **Identifying Highest Averages**: Find the species with the highest average 'petal_length' and 'sepal_length', offering insights into which species tends to have longer petals and sepals on average. (10pts)

In [21]:
# Task 4.1
grouped_means = iris_df.groupby('species').mean()
print(grouped_means)
print("\n")

# Task 4.2
species_counts = iris_df.value_counts('species')
print(species_counts)
print("\n")

# Task 4.3
max_avg_petal_length_species = iris_df.groupby('species')['petal_length'].mean().idxmax() 
max_avg_sepal_length_species = iris_df.groupby('species')['sepal_length'].mean().idxmax() 
print("Species with the highest average petal length:", max_avg_petal_length_species)
print("Species with the highest average sepal length:", max_avg_sepal_length_species)

                 sepal_length  sepal_width  petal_length  petal_width  \
species
Iris-versicolor         5.936        2.770         4.260        1.326
setosa                  5.006        3.428         1.462        0.246
virginica               6.588        2.974         5.552        2.026

                 speal_ratio
species
Iris-versicolor     2.160402
setosa              1.470188
virginica           2.230453


species
Iris-versicolor    50
setosa             50
virginica          50
Name: count, dtype: int64


Species with the highest average petal length: virginica
Species with the highest average sepal length: virginica